### ISSUE TITLE
Regarding The Game's Sprites

### ISSUE THREAD

**Issue by suvilocke** [Video-Game-Development-Club/first-game#2]
I'm not going to be here today - you know, AP Physics and such - so I decided to make a few points.

First of all, I don't know what games people are going to vote for, or if they're voting at all today, but I've started creating sprites already. I've been spriting for about four years, so please don't doubt my skill!

I have a very cute spriting style, if anyone is looking for that in a platformer, although I'm more or less limited to five or so precreated characters, with abilities I have not yet defined clearly. 

Anyhow...I had an idea for a game, potentially, if you guys are going to be discussing that. I assert, perhaps, that in a style similar to a megaman game, defeating a boss unlocks the boss as a playable character. That is all - because I REALLY want these sprites I'm making to be useable, if as a boss if not as a playable character.

I would put a file here, demonstrating the style which I use to sprite, but...I mean, I guess you could see my work at serio.piiym.net underneath the 'Castlevania Fighting Game' label. My work there isn't what I usually do, but it DOES demonstrate my skill.

I'm proud to be a part of this team! <3

**Comment by Bubadabado** [comment]
Awesome! We haven't decided completely if we're going to have meetings on Thursday so or not, so there is not a meeting today. Next meeting, on the other hand, I will send out a Google forms for game ideas.
